nodeLinker: node-modules
npmAlwaysAuth: false
npmRegistryServer: "https://registry.npmjs.org"
npmRegistries:
  "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/":
    npmAlwaysAuth: true
    npmAuthToken: "${CI_JOB_TOKEN}"

npmScopes:
  imapps:
    npmRegistryServer: "https://gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/"