name: Release (Reusable)

on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bunx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
